export const browserCoreExamples = [
  "hands browser status",
  "hands browser start",
  "hands browser stop",
  "hands browser tabs",
  "hands browser open https://example.com",
  "hands browser focus abcd1234",
  "hands browser close abcd1234",
  "hands browser screenshot",
  "hands browser screenshot --full-page",
  "hands browser screenshot --ref 12",
  "hands browser snapshot",
  "hands browser snapshot --format aria --limit 200",
  "hands browser snapshot --efficient",
  "hands browser snapshot --labels",
];

export const browserActionExamples = [
  "hands browser navigate https://example.com",
  "hands browser resize 1280 720",
  "hands browser click 12 --double",
  'hands browser type 23 "hello" --submit',
  "hands browser press Enter",
  "hands browser hover 44",
  "hands browser drag 10 11",
  "hands browser select 9 OptionA OptionB",
  "hands browser upload /tmp/file.pdf",
  'hands browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "hands browser dialog --accept",
  'hands browser wait --text "Done"',
  "hands browser evaluate --fn '(el) => el.textContent' --ref 7",
  "hands browser console --level error",
  "hands browser pdf",
];
